Repository VernonHawk/Brewtal, pull requests merged in 2018-06, with the labels that each got.

#8 Not so basic web server
  README.md
  package-lock.json
  package.json
  server.js
  server/awsConnect.js
  server/dynamoDB.js
  server/router.js
Labels: enhancement

#9 Items on table
  client/css/style.css
  client/img/svg/arrow-pointing-left.svg
  client/img/svg/arrow-pointing-right.svg
  client/img/svg/glass.svg
  client/img/svg/stone.svg
  client/index.html
  client/js/index.js
  client/parts/pagebar.html
Labels: enhancement

#11 Server coverage
  README.md
  package-lock.json
  package.json
  server.js
  test/client/test.js
  test/server/server.js
Labels: enhancement, good first issue

#13 Server adjustments
  package.json
  server/router.js
  server/server.js
  start.js
  test/server/server.js
Labels: enhancement, good first issue

#15 Major server refactoring
  server/awsConnect.js
  server/controllers/cocktailController.js
  server/controllers/ingredientsController.js
  server/dynamoDB.js
  server/router.js
  test/server/basicWork.js
  test/server/getCocktail.js
  test/server/getIngredients.js
Labels: enhancement

#21 Client cleaning
  client/css/style.css
  client/index.html
  client/js/glass.js
  client/js/index.js
  test/client/client.js
Labels: good first issue

#24 Added necessary tests lib
  package-lock.json
  package.json
Labels: good first issue

#25 Removed redundant functionality
  server/awsConnect.js
  server/controllers/cocktailController.js
  server/controllers/ingredientsController.js
  server/dynamoDB.js
  server/router.js
  test/server/getCocktail.js
Labels: good first issue

#27 Added cloudfront cdn for faster image loading
  server/controllers/ingredientsController.js
  test/server/getIngredients.js
Labels: enhancement

#29 Modal, tooltips and image saving
  .gitignore
  client/bundle.js
  client/css/style.css
  client/css/table.css
  client/index.html
  client/js/dom-to-image/dom-to-image.min.js
  client/js/index.js
  client/js/preloader.js
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#30 Fixed package-lock.json
  package-lock.json
Labels: bug

#31 Major release
  .gitignore
  client/bundle.js
  client/css/style.css
  client/css/table.css
  client/index.html
  client/js/dom-to-image/dom-to-image.min.js
  client/js/index.js
  client/js/preloader.js
  package-lock.json
  package.json
  server/awsConnect.js
  server/controllers/cocktailController.js
  server/controllers/ingredientsController.js
  server/dynamoDB.js
  server/router.js
  test/server/getCocktail.js
  test/server/getIngredients.js
  webpack.config.js
Labels: enhancement

#32 Fixed some bugs
  client/js/index.js
  client/js/preloader.js
Labels: bug

#36 Ingredients descriptions fix
  client/css/style.css
  client/js/main.js
Labels: bug, enhancement

#37 Fixed ingredients descriptions
  client/css/style.css
  client/js/main.js
Labels: enhancement
